Class {
	#name : #GtStreamingSpotterSearchWrongReturnError,
	#superclass : #Error,
	#instVars : [
		'definingMethod'
	],
	#category : #'GToolkit-Spotter-Exceptions'
}

{ #category : #accessing }
GtStreamingSpotterSearchWrongReturnError >> definingMethod [

	^ definingMethod
]

{ #category : #accessing }
GtStreamingSpotterSearchWrongReturnError >> definingMethod: anObject [

	definingMethod := anObject
]
