Extension { #name : #Pragma }

{ #category : #'*GToolkit-Spotter' }
Pragma >> gtSpotterForBytecodesFor: aStep [
	<gtSearch>
	self method spotterForBytecodesFor: aStep
]

{ #category : #'*GToolkit-Spotter' }
Pragma >> gtSpotterForImplementorsFor: aStep [
	<gtSearch>
	self method spotterForImplementorsFor: aStep
]

{ #category : #'*GToolkit-Spotter' }
Pragma >> gtSpotterForSendersFor: aStep [
	<gtSearch>
	self method spotterForSendersFor: aStep
]
